name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Playwright dependencies
        run: npm install playwright chromium
      - name: Run tests
        run: npm test
