name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fix playwright permissions
        run: |
          sh -c 'chmod +x ~/.local/bin/playwright'
      - name: Install Playwright dependencies
        run: npm install playwright chromium
        run: npm test

