name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fix playwright permissions and install dependencies
        run: |
          chmod +x ~/.local/bin/playwright
          npm install playwright chromium
      - name: Run tests
        run: npm test
